[req]
default_bits       = 2048
default_keyfile    = server.key
distinguished_name = req_distinguished_name
x509_extensions    = v3_req
prompt             = no

[req_distinguished_name]
C = US
ST = Local
L = Local
O = Dev
CN = 192.168.1.28

[v3_req]
subjectAltName = @alt_names

[alt_names]
IP.1 = 192.168.1.28
